P8105\_hw2\_sy2825
================
Shuo Yan (sy2825)
2018-10-02

Problem 1
=========

For this problem we will focus on a NYC Transit data. First, let's input and clean the data.

``` r
NYC_Transit_data = 
  read.csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(line:route11, entry, vending, entrance_type, ada) %>%
  mutate(
    entry = ifelse(entry == "YES", TRUE, FALSE)
  )
```

I have imported the data and used `select` function to select the data I need, I have also converted the entry variable from character to a logical variable with `ifelse` function. Now the variables in this dataset are line, station name, station latitude, station longitude, routes served, entry, vending, entrance type, and ADA compliance. And the dimension of this dataset is 1868, 19. These data are not tidy.

\*How many distinct stations are there?

``` r
nrow(
      distinct(NYC_Transit_data, station_name, line)
        )
```

    ## [1] 465

So there are 465 distinct stations.

\*How many stations are ADA compliant?

``` r
nrow(
      filter(NYC_Transit_data, ada == TRUE) %>%
      distinct(station_name, line)
        )
```

    ## [1] 84

So there are 84 stations are ADA compliant.

\*What proportion of station entrances / exits without vending allow entrance?

``` r
nrow(
      filter(NYC_Transit_data, vending == "NO") %>%
      distinct(station_name, line)
        ) / 465 
```

    ## [1] 0.2129032

So the proportion is about 21.3%.

Now let's reformat the data to make route number and route name are distinct variables.

``` r
NYC_Transit_data_reformat = gather(NYC_Transit_data, key = "route_number", value = "route_name", route1:route11)
```

    ## Warning: attributes are not identical across measure variables;
    ## they will be dropped

\*How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?

``` r
nrow(
      filter(NYC_Transit_data_reformat, route_name == "A") %>%
      distinct(station_name, line)
        )
```

    ## [1] 60

So there are 60 distinct stations serve the A train.

``` r
nrow(
     filter(NYC_Transit_data_reformat, route_name == "A", ada == TRUE) %>%
      distinct(station_name, line)
)
```

    ## [1] 17

So 17 of the distinct stations whcih serves the A train are ADA compliant.
